name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Container Registry Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker Build
        run: docker build . -t ghcr.io/${{ github.repository }}:latest
      - name: Docker  Push
        run: docker push ghcr.io/${{ github.repository }}:latest

permissions:
  contents: read
  packages: write
