name: ci

on:
  pull_request:
    branches:
        - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Run format
        run: test -z $(gofmt -l .)
      - name: Run staticcheck
        run: go vet ./...
      - name: Run tests
        run: go test
      - name: Run build
        run: go build .
